export const colors = {
  light: {
    background: "#F8F7F4",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#1A1A1A",
    primaryForeground: "#FFFFFF",
    secondary: "#F0EDE8",
    secondaryForeground: "#6B6B6B",
    muted: "#F0EDE8",
    mutedForeground: "#999999",
    accent: "#E8E4DD",
    accentForeground: "#1A1A1A",
    destructive: "#E5484D",
    destructiveForeground: "#FFFFFF",
    border: "#E8E4DD",
    input: "#E8E4DD",
    ring: "#1A1A1A",
    // quotes-specific
    quoteBackground: "#FFFFFF",
    quoteBorder: "rgba(0,0,0,0.06)",
    glassOverlay: "rgba(255,255,255,0.7)",
    iconDefault: "#BBBBBB",
    iconActive: "#1A1A1A",
    separator: "rgba(0,0,0,0.06)",
  },
  dark: {
    background: "#0A0A0A",
    foreground: "#ECECEC",
    card: "#161616",
    cardForeground: "#ECECEC",
    primary: "#ECECEC",
    primaryForeground: "#0A0A0A",
    secondary: "#1C1C1C",
    secondaryForeground: "#999999",
    muted: "#1C1C1C",
    mutedForeground: "#777777",
    accent: "#222222",
    accentForeground: "#ECECEC",
    destructive: "#E5484D",
    destructiveForeground: "#FFFFFF",
    border: "#222222",
    input: "#333333",
    ring: "#ECECEC",
    // quotes-specific
    quoteBackground: "#161616",
    quoteBorder: "rgba(255,255,255,0.06)",
    glassOverlay: "rgba(0,0,0,0.6)",
    iconDefault: "#555555",
    iconActive: "#ECECEC",
    separator: "rgba(255,255,255,0.06)",
  },
} as const;

export const fonts = {
  serif: "Lora",
  sans: "DMSans",
  sansBold: "DMSansBold",
  serifBold: "LoraBold",
  mono: "SpaceMono",
} as const;

export const radius = 16;
